# Generated by Django 5.1.1 on 2024-09-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='original',
            field=models.TextField(default='testing'),
            preserve_default=False,
        ),
    ]
